set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_AR aarch64-linux-gnu-ar CACHE FILEPATH "ARM64 archiver")
set(CMAKE_LINKER aarch64-linux-gnu-ld CACHE FILEPATH "ARM64 linker")
set(CMAKE_NM aarch64-linux-gnu-nm CACHE FILEPATH "ARM64 symbol tool")
set(CMAKE_OBJCOPY aarch64-linux-gnu-objcopy CACHE FILEPATH "ARM64 objcopy")
set(CMAKE_OBJDUMP aarch64-linux-gnu-objdump CACHE FILEPATH "ARM64 objdump")
set(CMAKE_RANLIB aarch64-linux-gnu-ranlib CACHE FILEPATH "ARM64 ranlib")
set(CMAKE_STRIP aarch64-linux-gnu-strip CACHE FILEPATH "ARM64 strip")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
