option(RKAVP_FETCH_DEPS "Download missing dependencies into 3rdparty/src" ON)
option(RKAVP_FORCE_FETCH_DEPS "Ignore installed packages and fetch dependencies" OFF)
option(RKAVP_BUILD_TESTS "Build host unit and integration tests" ON)
option(RKAVP_BUILD_EXAMPLES "Build framework API examples" OFF)
option(RKAVP_BUILD_HARDWARE_TESTS "Build tests requiring Rockchip hardware" OFF)
option(RKAVP_ENABLE_ROCKCHIP "Build MPP/RGA/RKNN backends" OFF)
option(RKAVP_ENABLE_AUDIO "Build ALSA backend" OFF)
option(RKAVP_ENABLE_STREAMING "Build ZLMediaKit backend" OFF)
option(RKAVP_ENABLE_OPENCL "Build optional OpenCL compute backend" OFF)
option(RKAVP_ENABLE_PYTHON "Build Python bindings" OFF)
option(RKAVP_ENABLE_SANITIZERS "Enable AddressSanitizer and UndefinedBehaviorSanitizer" OFF)
option(RKAVP_ENABLE_THREAD_SANITIZER "Enable ThreadSanitizer" OFF)
option(RKAVP_ENABLE_COVERAGE "Enable coverage instrumentation" OFF)

set(RKAVP_TARGET_SOC "host" CACHE STRING "Target SoC: host, rk3588, or rk3576")
set_property(CACHE RKAVP_TARGET_SOC PROPERTY STRINGS host rk3588 rk3576)

if(RKAVP_ENABLE_SANITIZERS AND RKAVP_ENABLE_THREAD_SANITIZER)
  message(FATAL_ERROR "ASan/UBSan and TSan cannot be enabled together")
endif()

if(RKAVP_ENABLE_SANITIZERS)
  add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
  add_link_options(-fsanitize=address,undefined)
endif()

if(RKAVP_ENABLE_THREAD_SANITIZER)
  add_compile_options(-fsanitize=thread -fno-omit-frame-pointer)
  add_link_options(-fsanitize=thread)
endif()

if(RKAVP_ENABLE_COVERAGE)
  add_compile_options(--coverage -O0 -g)
  add_link_options(--coverage)
endif()
